apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: dag-diamond-
spec:
  entrypoint: diamond
  templates:
  - name: diamond
    dag:
      tasks:
      - name: A
        template: echo
      - name: B
        dependencies: ["A"]
        template: echo

  - name: echo
    retryStrategy:
      limit: 10
      backoff:
        duration: "1"
        maxDuration: "5"
    container:
      image: alpine:3.7
      command: [sh, -c]
      args: ["exit 1"]
